### ISSUE TITLE
Atención - Causas de rechazo de Pull-Request

### ISSUE THREAD

**Issue by piraces** [piraces/Wallapet#16]
A partir de este momento, no se aceptara ningún pull-request que contenga archivos de configuración (gradle scripts, .idea, etc.).

A modo de excepción los ficheros xml de la carpeta "res" y "AndroidManifest.xml" pueden ser incluidos en el pull request.

Antes de realizar ningún pull-request se debe actualizar el proyecto desde la ultima version del branch "master". Si se han producido cambios en master mientras estabas desarrollando deberas actualizarlo a la ultima version de master.

Esto es importante ya que los pull-request se complican, aumenta el trabajo y podemos perder cambios.

**Comment by ismaelrh** [comment]
Me parece bien, además si tu repo tiene archivos de .idea, gradle etc, luego al hacer rebase se carga todo y no hay quien compile.  :+1:
