### ISSUE TITLE
Operaciones de red en hilo principal

### ISSUE THREAD

**Issue by ismaelrh** [piraces/Wallapet#18]
Actualmente las peticiones de red se hacen en el hilo principal de GUI. Esto está totalmente desaconsejado y ralentiza el programa. 
En un futuro próximo habrá que realizar las tareas de red en un segundo hilo creado para tal efecto.
Si no está hecho aún ha sido por las prisas que corre tener la aplicación hecha.

**Comment by piraces** [comment]
Si además no se a partir de cual versión de android es obligatorio que todas las conexiones se realizen en un hilo aparte ya que no puedes dejar bloqueada la pantalla principal... Asi que habra que cambiarlo en un futuro.

**Comment by ismaelrh** [comment]
Efectivamente es obligatorio, pero puede deshabilitarse la restriccion q es
lo que he hecho para salir del paso

**Comment by piraces** [comment]
Esto esta terminado ya no?

**Comment by ismaelrh** [comment]
No lo está pero seguramente por falta de tiempo se deje así

**Comment by piraces** [comment]
Ahora yo creo que nos dara tiempo... Si no solo hace falta añadir las dos lineas en el metodo OnCreateView() de cada clase que utilize internet:

> StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
> StrictMode.setThreadPolicy(policy);
