### ISSUE TITLE
Subir imágenes mediante server.

### ISSUE THREAD

**Issue by piraces** [piraces/Wallapet#26]
Actualmente se suben directamente a la BD como tipo de dato "long blob".
En un futuro tendrian que ser subidas mediante un POST al server y almacenadas en el.

**Comment by ismaelrh** [comment]
Y al hacer consulta mediante la interfaz web envía la imagen? Sin quiero
obtener un listado, y va a enviar las imágenes... Habrá que retocar el
servidor para ofrecer métodos de listado sin imagen.

**Comment by piraces** [comment]
Cierto...

**Comment by piraces** [comment]
Arreglado, las imagenes se suben al server mediante post en un php.
