### ISSUE TITLE
Aumentar seguridad de la aplicación

### ISSUE THREAD

**Issue by piraces** [piraces/Wallapet#27]
Aumentar seguridad en general de toda la aplicación para evitar posibles ataques o trolleos.

**Comment by piraces** [comment]
Arreglado.

**Comment by ismaelrh** [comment]
La aplicación es vulnerable a inyección SQL.

**Comment by piraces** [comment]
¿En que parte podrías inyectar código SQL? Si me lo dices lo arreglo hoy.

**Comment by ssoro7** [comment]
en cualquier formulario de entrada

2015-05-05 16:17 GMT+02:00 Raul Piraces Alastuey notifications@github.com:
